export enum ActionTypes {
  TOGGLE_MATRIX,
  POST_BFS_FAILURE,
  FETCH_WEIGHTED_ROUTE_REQUEST,
  FETCH_WEIGHTED_ROUTE_SUCCESS,
  FETCH_WEIGHTED_ROUTE_FAILURE,
  POST_NEW_ROUTE_REQUEST,
  UPDATE_MAP_TEXT,
  POST_BFS_REQUEST,
  POST_BFS_SUCCESS,
}